FROM php:7.4-apache

# Install (but also activate mysqli extension)
RUN docker-php-ext-install mysqli

# Create default certificates directory
RUN mkdir -p /etc/apache2/default_ssl

# Activate SSL
RUN a2enmod ssl && a2enmod rewrite

# Activate htaccess
RUN a2enmod authz_core 
RUN a2enmod authz_groupfile

# Change permissions and group htpasswd
RUN chmod 640 .src/.htpasswd
RUN chown root:www-data ./src/.htpasswd

# Copy default ssl files
COPY ./default_ssl/fullchain.pem /etc/apache2/default_ssl/fullchain.pem
COPY ./default_ssl/privkey.pem /etc/apache2/default_ssl/privkey.pem

# Copy apache config
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf

# Copy app code into container apache web directory
COPY ./src /var/www/html

# Expose port HTTP and HTTPS
EXPOSE 80
EXPOSE 443